---

- name: "Compute SFTP users."
  set_fact:
    _sftp_users: >-
      [{% for sftp_user in sftp_users -%}
        {{ sftp_user | combine({'home': sftp_user.home | default(sftp_home_partition + '/' + sftp_user.name) }) }}
        {{ '' if loop.last else ',' }}
      {%- endfor %}]

- name: SFTP-Server | Create sftp user group
  group:
    name: "{{ sftp_group_name }}"
    state: present

- name: SFTP-Server | Alter sftp subsystem entry
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Subsystem(\s+)sftp'
    line: "Subsystem sftp internal-sftp -f AUTH -l VERBOSE"
    state: present
  notify: SFTP-Server | Restart sshd

- name: SFTP-Server | Ensure SELinux management package is present
  package:
    name: "{{ 'python-semanage' if ansible_distribution == 'Debian' else 'libsemanage-python' }}"
    state: present
  when: ansible_selinux and sftp_enable_selinux_support

- name: SFTP-Server | Set SELinux booleans
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - ssh_chroot_full_access
    - ssh_chroot_rw_homedirs
  when: ansible_selinux and sftp_enable_selinux_support

- name: SFTP-Server | Add sshd_config block
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark} SFTP-Server {{ sftp_group_name }} block"
    block: |
      Match Group {{ sftp_group_name }}
          ChrootDirectory %h
          AllowTCPForwarding no
          PermitTunnel no
          X11Forwarding no
          ForceCommand internal-sftp {{ sftp_enable_logging | ternary('-l VERBOSE', '') }} {{ (sftp_start_directory in sftp_directories or sftp_start_directory in sftp_directories | selectattr("name", "defined") | map(attribute='name') | list) | ternary('-d /' + sftp_start_directory, '') }}
          PasswordAuthentication {{ sftp_allow_passwords | ternary('yes', 'no') }}
  notify: SFTP-Server | Restart sshd
