---

- name: SFTP-Server | Create sftp user's group
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ _sftp_users | selectattr('group', 'defined') | map(attribute='group') | list }}"

- name: SFTP-Server | Create sftp users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ sftp_group_name }}"
    append: "{{ item.append | default(False) }}"
    home: "{{ item.home }}"
    shell: "{{ None if (item.shell | default(True)) else sftp_nologin_shell }}"
    skeleton: "{{ item.skeleton | default(omit) }}"
    state: present
  with_items: "{{ _sftp_users }}"
