---

- name: SFTP-Server | Create dev directory for logging
  file:
    path: "{{ item.home }}/dev"
    owner: root
    group: root
    state: directory
  with_items:
    - "{{ _sftp_users }}"
  when: sftp_enable_logging

- name: SFTP-Server | Enable Logging
  copy:
    dest: "/etc/rsyslog.d/sftp.conf"
    content: |
      # Create an additional socket for some of the sshd chrooted users.
      {% for user in sftp_users %}
      $AddUnixListenSocket {{ sftp_home_partition }}/{{ user.name }}/dev/log
      {% endfor %}

      # Log internal-sftp in a separate file
      :programname, isequal, "internal-sftp" -/var/log/sftp.log
      :programname, isequal, "internal-sftp" ~
  when: sftp_enable_logging
  notify: SFTP-Server | Restart rsyslog

- name: SFTP-Server | Enable Log rotation
  copy:
    dest: "/etc/logrotate.d/sftp"
    content: |
      /var/log/sftp.log
      {
        rotate 4
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
      }
  when: sftp_enable_logging
