---

- name: Include create_partition tasks
  include_tasks: create_partition.yml

- name: Include configure_sftp tasks
  include_tasks: configure_sftp.yml

- name: Include create_users tasks
  include_tasks: create_users.yml

- name: Include set_permissions tasks
  include_tasks: set_permissions.yml

- name: Include install_keys tasks
  include_tasks: install_keys.yml

- name: Include update_passwords tasks
  include_tasks: update_passwords.yml

- name: Include create_directories tasks
  include_tasks: create_directories.yml

- name: Include enable_logging tasks
  include_tasks: enable_logging.yml
