---

- name: SFTP-Server | Create sftp home partition
  file:
    path: "{{ sftp_home_partition }}"
    state: directory

- name: SFTP-Server | Create directories for all SFTP users
  file:
    path: "{{ item[0].home }}/{{ item[1].name | default(item[1]) }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].group | default(item[0].name) }}"
    mode: "{{ item[1].mode | default('0750') }}"
    state: directory
  with_nested:
    - "{{ _sftp_users }}"
    - "{{ sftp_directories }}"

- name: SFTP-Server | Create symbolic link and set permissions
  command: ln -s "{{ sftp_home_partition }}/{{ item.user_link }}/{{ item.folder }}" "{{ sftp_home_partition }}/{{ item.user_base }}/{{ item.folder }}"
  with_items: "{{ sftp_links }}"
  when: sftp_links is defined and sftp_links | length > 0 and item.user_link is defined and item.user_base is defined and item.folder is defined

- name: SFTP-Server | Set permissions for linked folder
  command: chmod 770 "{{ sftp_home_partition }}/{{ item.user_base }}/{{ item.folder }}"
  with_items: "{{ sftp_links }}"
  when: sftp_links is defined and sftp_links | length > 0 and item.user_link is defined and item.user_base is defined and item.folder is defined
