---

- name: SFTP-Server | Create sftp home partition
  file:
    path: "{{ sftp_home_partition }}"
    state: directory

- name: SFTP-Server | Create directories for all SFTP users
  file:
    path: "{{ item[0].home }}/{{ item[1].name | default(item[1]) }}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].group | default(item[0].name) }}"
    mode: "{{ item[1].mode | default('0750') }}"
    state: directory
  with_nested:
    - "{{ _sftp_users }}"
    - "{{ sftp_directories }}"
