---

name: Molecule Test MariaDB
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash
    working-directory: steamulo.steambuly

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-22.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: steamulo.steambuly

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Start systemd user service
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Run all molecule tests
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: |
          molecule test --all
