name: Ansible Role Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, centos-7, centos-8]
        ansible-version: [2.9, 2.10] # Updated versions
        exclude: # Exclude centos-8 with Ansible 2.5 and 2.9
          - os: centos-8
            ansible-version: 2.9
          - os: centos-8
            ansible-version: 2.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Ansible
        run: pip3 install "ansible==${{ matrix.ansible-version }}"

      - name: Run Docker container
        run: |
          docker pull ${{ matrix.os }}:latest
          docker build --rm=true --file=tests/Dockerfile.${{ matrix.os }}.ansible-${{ matrix.ansible-version }} --tag=${{ matrix.os }}-ansible-${{ matrix.ansible-version }} tests
          container_id=$(mktemp)
          docker run --rm=true --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${{ matrix.os }}-ansible-${{ matrix.ansible-version }} /sbin/init > "${container_id}"
          docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
          docker stop "$(cat ${container_id})"
