name: Molecule Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

defaults:
  run:
    shell: bash
    working-directory: steamulo.sftp

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        ubuntu-version: [24.04]
        scenario: [lint, one, two, all]
      fail-fast: false  # Continue running other tests even if one fails
    steps:
      - uses: actions/checkout@v4
        with:
          path: steamulo.sftp
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Print working directory
        run: pwd
      - name: Run molecule ${{ matrix.scenario }}
        env:
          MOLECULE_DISTRO: "ubuntu${{ matrix.ubuntu-version }}"
        run: |
          molecule ${{ matrix.scenario }}
